### ISSUE TITLE
Panic while docker stop miner.

### ISSUE THREAD

**Issue by getlai** [CovenantSQL/CovenantSQL#125]
```
time="2018-11-20T07:04:28Z" level=info msg="kayak leader apply" dc=205724 dq=826 eq=1578 fc=2358469 fp=9535526 fr=0 lc=251642 lp=7597386 r=534948 t=19745427
time="2018-11-20T07:04:28Z" level=info msg="kayak leader apply" dc=7554366 dq=719 eq=1008 fc=8217140 fp=3894101 fr=0 lc=7592117 lp=494967 r=534950 t=20200052
time="2018-11-20T07:04:28Z" level=info msg="miner stopped"
time="2018-11-20T07:04:28Z" level=info msg="Stopping Server Loop"
time="2018-11-20T07:04:28Z" level=panic msg="WRITE LOG FAILED: wal is closed" caller="runtime.go:763 kayak.(*Runtime).newLog" stack="[#0 kayak.(*Runtime).newLog@runtime.go:763      #1 kayak.(*Runtime).leaderLogPrepare@runtime.go:457      #2 kayak.(*Runtime).Apply@runtime.go:319      #3 worker.(*Database).writeQuery@db.go:323      #4 worker.(*Database).Query@db.go:222      #5 worker.(*DBMS).Query@dbms.go:272      #6 worker.(*DBMSRPCService).Query@dbms_rpc.go:75      #7 runtime.call64@asm_amd64.s:523      #8 reflect.Value.call@value.go:447     ]"
time="2018-11-20T07:04:28Z" level=info msg="kayak leader apply" dq=0 eq=0 fc=0 fp=0 fr=0 lc=0 lr=0 r=0
panic: (*logrus.Entry) (0xf036c0,0xc01c5fd140)

goroutine 1469237 [running]:
github.com/CovenantSQL/CovenantSQL/vendor/github.com/sirupsen/logrus.Entry.log(0xc00009a120, 0xc00485f500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/CovenantSQL/CovenantSQL/vendor/github.com/sirupsen/logrus/entry.go:216 +0x2cf
github.com/CovenantSQL/CovenantSQL/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc0194cecc0, 0xc02449d5d0, 0x1, 0x1)
	/go/src/github.com/CovenantSQL/CovenantSQL/vendor/github.com/sirupsen/logrus/entry.go:290 +0xab
github.com/CovenantSQL/CovenantSQL/vendor/github.com/sirupsen/logrus.(*Entry).Panicf(0xc0194cecc0, 0xf26313, 0x14, 0xc02449d708, 0x1, 0x1)
	/go/src/github.com/CovenantSQL/CovenantSQL/vendor/github.com/sirupsen/logrus/entry.go:344 +0xed
github.com/CovenantSQL/CovenantSQL/vendor/github.com/sirupsen/logrus.(*Logger).Panicf(0xc00009a120, 0xf26313, 0x14, 0xc02449d708, 0x1, 0x1)
	/go/src/github.com/CovenantSQL/CovenantSQL/vendor/github.com/sirupsen/logrus/logger.go:200 +0x85
github.com/CovenantSQL/CovenantSQL/vendor/github.com/sirupsen/logrus.Panicf(0xf26313, 0x14, 0xc02449d708, 0x1, 0x1)
	/go/src/github.com/CovenantSQL/CovenantSQL/vendor/github.com/sirupsen/logrus/exported.go:168 +0x5f
github.com/CovenantSQL/CovenantSQL/utils/log.Fatalf(0xf26313, 0x14, 0xc02449d708, 0x1, 0x1)
	/go/src/github.com/CovenantSQL/CovenantSQL/utils/log/logwrapper.go:317 +0x53
github.com/CovenantSQL/CovenantSQL/kayak.(*Runtime).newLog(0xc0000662c0, 0xb20000, 0xc031cc9c00, 0x5ea, 0xa88, 0x0, 0x0, 0x11ac660f4df)
	/go/src/github.com/CovenantSQL/CovenantSQL/kayak/runtime.go:763 +0x148
github.com/CovenantSQL/CovenantSQL/kayak.(*Runtime).leaderLogPrepare(0xc0000662c0, 0xc031cc9c00, 0x5ea, 0xa88, 0x5ea, 0xa88, 0x0)
	/go/src/github.com/CovenantSQL/CovenantSQL/kayak/runtime.go:457 +0x50
github.com/CovenantSQL/CovenantSQL/kayak.(*Runtime).Apply(0xc0000662c0, 0x11404e0, 0xc000096060, 0xe98140, 0xc031e63e00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/CovenantSQL/CovenantSQL/kayak/runtime.go:319 +0x321
github.com/CovenantSQL/CovenantSQL/worker.(*Database).writeQuery(0xc0001f62d0, 0xc031e63e00, 0x0, 0x0, 0x0)
	/go/src/github.com/CovenantSQL/CovenantSQL/worker/db.go:323 +0x17f
github.com/CovenantSQL/CovenantSQL/worker.(*Database).Query(0xc0001f62d0, 0xc031e63e00, 0x40, 0xc0001f62d0, 0x1)
	/go/src/github.com/CovenantSQL/CovenantSQL/worker/db.go:222 +0x49
github.com/CovenantSQL/CovenantSQL/worker.(*DBMS).Query(0xc00001e410, 0xc031e63e00, 0x40, 0xd32aa17dd4e2d01, 0xc0372ee240)
	/go/src/github.com/CovenantSQL/CovenantSQL/worker/dbms.go:272 +0x68
github.com/CovenantSQL/CovenantSQL/worker.(*DBMSRPCService).Query(0xc00000e228, 0xc031e63e00, 0xc008786b60, 0x0, 0x0)
	/go/src/github.com/CovenantSQL/CovenantSQL/worker/dbms_rpc.go:75 +0x1db
reflect.Value.call(0xc0000692c0, 0xc00000e2a8, 0x13, 0xf18f02, 0x4, 0xc00032df18, 0x3, 0x3, 0xc037243740, 0x8, ...)
	/usr/local/go/src/reflect/value.go:447 +0x449
reflect.Value.Call(0xc0000692c0, 0xc00000e2a8, 0x13, 0xc000040f18, 0x3, 0x3, 0xe71200, 0xc00025b640, 0x1139580)
	/usr/local/go/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc00009d840, 0xc00001e370, 0xc01f593be0, 0xc01f593bf0, 0xc000020c80, 0xc004762200, 0xe98140, 0xc031e63e00, 0x16, 0xe2d8e0, ...)
	/usr/local/go/src/net/rpc/server.go:384 +0x14e
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:481 +0x47e
```

**Comment by auxten** [comment]
outdated
