### ISSUE TITLE
signal SIGBUS: bus error code

### ISSUE THREAD

**Issue by draveness** [CovenantSQL/CovenantSQL#151]
```
covenantsql_observer         | time="2018-12-23T07:35:53Z" level=debug msg="PingBP resp: &proto.PingResp{Msg:\"Pong\", Envelope:proto.Envelope{Version:\"\", TTL:0, Expire:0, NodeID:(*proto.RawNodeID)(nil), _ctx:context.Context(nil)}}"
covenantsql_observer         | unexpected fault address 0x7f47b829a040
covenantsql_observer         | fatal error: fault
covenantsql_observer         | [signal SIGBUS: bus error code=0x2 addr=0x7f47b829a040 pc=0x93e9db]
covenantsql_observer         |
covenantsql_observer         | goroutine 5 [running]:
covenantsql_observer         | runtime.throw(0xd74b5c, 0x5)
covenantsql_observer         | 	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0000508d8 sp=0xc0000508a8 pc=0x42e162
covenantsql_observer         | runtime.sigpanic()
covenantsql_observer         | 	/usr/local/go/src/runtime/signal_unix.go:387 +0x2d7 fp=0xc000050928 sp=0xc0000508d8 pc=0x443477
covenantsql_observer         | github.com/CovenantSQL/CovenantSQL/vendor/github.com/coreos/bbolt.(*DB).meta(0xc0001183c0, 0xc00023a0c0)
covenantsql_observer         | 	/go/src/github.com/CovenantSQL/CovenantSQL/vendor/github.com/coreos/bbolt/db.go:808 +0x3b fp=0xc000050978 sp=0xc000050928 pc=0x93e9db
covenantsql_observer         | github.com/CovenantSQL/CovenantSQL/vendor/github.com/coreos/bbolt.(*Tx).init(0xc0002ae0e0, 0xc0001183c0)
covenantsql_observer         | 	/go/src/github.com/CovenantSQL/CovenantSQL/vendor/github.com/coreos/bbolt/tx.go:50 +0xa2 fp=0xc000050a18 sp=0xc000050978 pc=0x944b52
covenantsql_observer         | github.com/CovenantSQL/CovenantSQL/vendor/github.com/coreos/bbolt.(*DB).beginTx(0xc0001183c0, 0xc3e2e0, 0x7f47bc7d7000, 0x0)
covenantsql_observer         | 	/go/src/github.com/CovenantSQL/CovenantSQL/vendor/github.com/coreos/bbolt/db.go:486 +0x99 fp=0xc000050a88 sp=0xc000050a18 pc=0x93d5e9
covenantsql_observer         | github.com/CovenantSQL/CovenantSQL/vendor/github.com/coreos/bbolt.(*DB).Begin(0xc0001183c0, 0x4d5f00, 0xc000050af8, 0x40f608, 0x8)
covenantsql_observer         | 	/go/src/github.com/CovenantSQL/CovenantSQL/vendor/github.com/coreos/bbolt/db.go:463 +0x6e fp=0xc000050ab8 sp=0xc000050a88 pc=0x93d51e
covenantsql_observer         | github.com/CovenantSQL/CovenantSQL/vendor/github.com/coreos/bbolt.(*DB).View(0xc0001183c0, 0xc000050b30, 0x0, 0x0)
covenantsql_observer         | 	/go/src/github.com/CovenantSQL/CovenantSQL/vendor/github.com/coreos/bbolt/db.go:610 +0x3c fp=0xc000050b08 sp=0xc000050ab8 pc=0x93debc
covenantsql_observer         | main.(*Service).getHighestBlockV2(0xc0000a1590, 0xc0002a400d, 0x40, 0x0, 0xc0002b2748, 0xd28ba0, 0xc00022a300)
covenantsql_observer         | 	/go/src/github.com/CovenantSQL/CovenantSQL/cmd/cql-observer/service.go:694 +0xbe fp=0xc000050b70 sp=0xc000050b08 pc=0xa619fe
covenantsql_observer         | main.(*explorerAPI).GetHighestBlockV2(0xc000142258, 0xf6b8c0, 0xc0002ae000, 0xc000228700)
covenantsql_observer         | 	/go/src/github.com/CovenantSQL/CovenantSQL/cmd/cql-observer/api.go:349 +0xf0 fp=0xc000050bf0 sp=0xc000050b70 pc=0xa57df0
covenantsql_observer         | main.(*explorerAPI).GetHighestBlockV2-fm(0xf6b8c0, 0xc0002ae000, 0xc000228700)
covenantsql_observer         | 	/go/src/github.com/CovenantSQL/CovenantSQL/cmd/cql-observer/api.go:573 +0x48 fp=0xc000050c20 sp=0xc000050bf0 pc=0xa656a8
covenantsql_observer         | net/http.HandlerFunc.ServeHTTP(0xc00013f8c0, 0xf6b8c0, 0xc0002ae000, 0xc000228700)
covenantsql_observer         | 	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc000050c48 sp=0xc000050c20 pc=0x6925c4
covenantsql_observer         | github.com/CovenantSQL/CovenantSQL/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001aa460, 0xf6b8c0, 0xc0002ae000, 0xc000228700)
covenantsql_observer         | 	/go/src/github.com/CovenantSQL/CovenantSQL/vendor/github.com/gorilla/mux/mux.go:162 +0xf1 fp=0xc000050d48 sp=0xc000050c48 pc=0x960d41
covenantsql_observer         | net/http.serverHandler.ServeHTTP(0xc000124a90, 0xf6b8c0, 0xc0002ae000, 0xc000228500)
covenantsql_observer         | 	/usr/local/go/src/net/http/server.go:2741 +0xab fp=0xc000050d78 sp=0xc000050d48 pc=0x69522b
covenantsql_observer         | net/http.(*conn).serve(0xc00022c0a0, 0xf6c280, 0xc000064540)
covenantsql_observer         | 	/usr/local/go/src/net/http/server.go:1847 +0x646 fp=0xc000050fc8 sp=0xc000050d78 pc=0x691626
covenantsql_observer         | runtime.goexit()
covenantsql_observer         | 	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000050fd0 sp=0xc000050fc8 pc=0x45ba41
covenantsql_observer         | created by net/http.(*Server).Serve
covenantsql_observer         | 	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by auxten** [comment]
fixed
