### ISSUE TITLE
[BUG] Compiling with go 1.13.4 on macOS Catalina leads to segfault

### ISSUE THREAD

**Issue by fxcoudert** [CovenantSQL/CovenantSQL#370]
**To Reproduce**

1. Build with go 1.13.4 on macOS
2. Run `cql generate`: 

```
==> /usr/local/Cellar/cql/0.8.0/bin/cql generate /private/tmp/cql-test-20191102-86418-1intxwf/confgen
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff68322476]

runtime stack:
runtime.throw(0x4d70a61, 0x2a)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4acd2c0, 0xc0000efdf8, 0x4d7ce82)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc0000efdc8 sp=0xc0000efd90 pc=0x4004beb
github.com/CovenantSQL/CovenantSQL/crypto/secp256k1._Cfunc_secp256k1_context_create_sign_verify(0x0)
	_cgo_gotypes.go:170 +0x4a fp=0xc0000efdf8 sp=0xc0000efdc8 pc=0x43ba70a
github.com/CovenantSQL/CovenantSQL/crypto/secp256k1.init.1()
	/private/tmp/cql-20191102-84097-c1dwy1/CovenantSQL-0.8.0/src/github.com/CovenantSQL/CovenantSQL/crypto/secp256k1/secp256.go:38 +0x22 fp=0xc0000efe10 sp=0xc0000efdf8 pc=0x43bd202
runtime.doInit(0x59ccec0)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:5222 +0x8a fp=0xc0000efe40 sp=0xc0000efe10 pc=0x403e9fa
runtime.doInit(0x59d0420)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:5217 +0x57 fp=0xc0000efe70 sp=0xc0000efe40 pc=0x403e9c7
runtime.doInit(0x59d2860)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:5217 +0x57 fp=0xc0000efea0 sp=0xc0000efe70 pc=0x403e9c7
runtime.doInit(0x59d0ee0)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:5217 +0x57 fp=0xc0000efed0 sp=0xc0000efea0 pc=0x403e9c7
runtime.doInit(0x59ccf80)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:5217 +0x57 fp=0xc0000eff00 sp=0xc0000efed0 pc=0x403e9c7
runtime.doInit(0x59d7500)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:5217 +0x57 fp=0xc0000eff30 sp=0xc0000eff00 pc=0x403e9c7
runtime.doInit(0x59cd280)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:5217 +0x57 fp=0xc0000eff60 sp=0xc0000eff30 pc=0x403e9c7
runtime.main()
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:190 +0x1da fp=0xc0000effe0 sp=0xc0000eff60 pc=0x403268a
runtime.goexit()
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000effe8 sp=0xc0000effe0 pc=0x405ef21
```

**Desktop (please complete the following information):**
 - OS: macOS Catalina (10.15)
 - Go Version: 1.13.4
 - Cql Version: 0.8.0

**Comment by fxcoudert** [comment]
This was uncovered during part of building Homebrew binaries for macOS Catalina.
